//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanitta {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yanitta.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список способностей.
        /// </summary>
        public static string AbilityList {
            get {
                return ResourceManager.GetString("AbilityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на События.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новую способность.
        /// </summary>
        public static string AddAbility {
            get {
                return ResourceManager.GetString("AddAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новый профиль.
        /// </summary>
        public static string AddProfile {
            get {
                return ResourceManager.GetString("AddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новую ротацию.
        /// </summary>
        public static string AddRotation {
            get {
                return ResourceManager.GetString("AddRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступные способности.
        /// </summary>
        public static string AlavilableAbilitys {
            get {
                return ResourceManager.GetString("AlavilableAbilitys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код профиля.
        /// </summary>
        public static string BeforeRotationCode {
            get {
                return ResourceManager.GetString("BeforeRotationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот код выполняется при старте ротации.
        /// </summary>
        public static string BeforeRotationCodeToolTip {
            get {
                return ResourceManager.GetString("BeforeRotationCodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прерывать заклинания.
        /// </summary>
        public static string CancelCasting {
            get {
                return ResourceManager.GetString("CancelCasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прерывать чтение заклинаний.
        /// </summary>
        public static string CancelCastingToolTip {
            get {
                return ResourceManager.GetString("CancelCastingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прерывать потоковые.
        /// </summary>
        public static string CancelChanel {
            get {
                return ResourceManager.GetString("CancelChanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Cencel {
            get {
                return ResourceManager.GetString("Cencel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Класс.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть текущее окно.
        /// </summary>
        public static string CloseToolTip {
            get {
                return ResourceManager.GetString("CloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Консоль кода.
        /// </summary>
        public static string CodeConsole {
            get {
                return ResourceManager.GetString("CodeConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конструктор.
        /// </summary>
        public static string Constructor {
            get {
                return ResourceManager.GetString("Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скопировать текущую способность.
        /// </summary>
        public static string CopyAbility {
            get {
                return ResourceManager.GetString("CopyAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скопировать текущий профиль.
        /// </summary>
        public static string CopyProfile {
            get {
                return ResourceManager.GetString("CopyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скопировать текущую ротацию.
        /// </summary>
        public static string CopyRotation {
            get {
                return ResourceManager.GetString("CopyRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код ядра.
        /// </summary>
        public static string CoreHeader {
            get {
                return ResourceManager.GetString("CoreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Содержит код обработчика способностей.
        /// </summary>
        public static string CoreHeaderToolTip {
            get {
                return ResourceManager.GetString("CoreHeaderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущая ротация.
        /// </summary>
        public static string CurrentRotation {
            get {
                return ResourceManager.GetString("CurrentRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задержка.
        /// </summary>
        public static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить текущую способность.
        /// </summary>
        public static string DeleteAbility {
            get {
                return ResourceManager.GetString("DeleteAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить текущий профиль.
        /// </summary>
        public static string DeleteProfile {
            get {
                return ResourceManager.GetString("DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить текущию ротацию.
        /// </summary>
        public static string DeleteRotation {
            get {
                return ResourceManager.GetString("DeleteRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прерывать канальные заклинания..
        /// </summary>
        public static string DropChanelToolTip {
            get {
                return ResourceManager.GetString("DropChanelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор профилей.
        /// </summary>
        public static string EditorTitle {
            get {
                return ResourceManager.GetString("EditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить текущий профиль в файл.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общие функции.
        /// </summary>
        public static string GlobalFunk {
            get {
                return ResourceManager.GetString("GlobalFunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общие функции, которые можно использовать в написании ротации..
        /// </summary>
        public static string GlobalFunkToolTip {
            get {
                return ResourceManager.GetString("GlobalFunkToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помощь.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать справку.
        /// </summary>
        public static string HelpToolTip {
            get {
                return ResourceManager.GetString("HelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гарячая клавиша.
        /// </summary>
        public static string HotKey {
            get {
                return ResourceManager.GetString("HotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить профиль из файла.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возможность атаковать.
        /// </summary>
        public static string IsAttacedTarget {
            get {
                return ResourceManager.GetString("IsAttacedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возможность атаковать цель.
        /// </summary>
        public static string IsAttacedTargetToolTip {
            get {
                return ResourceManager.GetString("IsAttacedTargetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка на нахождение в бою.
        /// </summary>
        public static string IsInCombatToolTip {
            get {
                return ResourceManager.GetString("IsInCombatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без ГКД.
        /// </summary>
        public static string IsNotHCD {
            get {
                return ResourceManager.GetString("IsNotHCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указывает, что данная способность не имеет глобального кулдауна.
        /// </summary>
        public static string IsNotHCDToolTip {
            get {
                return ResourceManager.GetString("IsNotHCDToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка дистанции.
        /// </summary>
        public static string IsRangeCheck {
            get {
                return ResourceManager.GetString("IsRangeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка досягаемости цели (не работает для некоторых заклинаний).
        /// </summary>
        public static string IsRangeCheckToolTip {
            get {
                return ResourceManager.GetString("IsRangeCheckToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать в бою.
        /// </summary>
        public static string IsUseIncombat {
            get {
                return ResourceManager.GetString("IsUseIncombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить список способностей из файла.
        /// </summary>
        public static string LoadAbilityList {
            get {
                return ResourceManager.GetString("LoadAbilityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свернуть.
        /// </summary>
        public static string Minimise {
            get {
                return ResourceManager.GetString("Minimise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;XML файлы (*.xml)|*.xml|Все файлы (*.*)|*.*&quot;.
        /// </summary>
        public static string ProfileFileMask {
            get {
                return ResourceManager.GetString("ProfileFileMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезагрузить.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезагрузить профили из файла.
        /// </summary>
        public static string ReloadToolTip {
            get {
                return ResourceManager.GetString("ReloadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ротация.
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список ротаций.
        /// </summary>
        public static string RotationList {
            get {
                return ResourceManager.GetString("RotationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить текущий профиль.
        /// </summary>
        public static string SaveToolTip {
            get {
                return ResourceManager.GetString("SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задержка на произнесение следующего заклинания.
        /// </summary>
        public static string SetRecastDelay {
            get {
                return ResourceManager.GetString("SetRecastDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задержка на произнесение следующего этого заклинания.
        /// </summary>
        public static string SetRecastDelayToolTip {
            get {
                return ResourceManager.GetString("SetRecastDelayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звук.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заклинание.
        /// </summary>
        public static string Spell {
            get {
                return ResourceManager.GetString("Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цель.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип цели.
        /// </summary>
        public static string TargetToolTip {
            get {
                return ResourceManager.GetString("TargetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Долбилка.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверить обновление базы профилей.
        /// </summary>
        public static string UpdateToolTip {
            get {
                return ResourceManager.GetString("UpdateToolTip", resourceCulture);
            }
        }
    }
}
