//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanitta {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yanitta.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ability count: .
        /// </summary>
        public static string AbilityCount {
            get {
                return ResourceManager.GetString("AbilityCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ability list.
        /// </summary>
        public static string AbilityList {
            get {
                return ResourceManager.GetString("AbilityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Append new ability.
        /// </summary>
        public static string AddAbility {
            get {
                return ResourceManager.GetString("AddAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Append new profile.
        /// </summary>
        public static string AddProfile {
            get {
                return ResourceManager.GetString("AddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на append new rotation.
        /// </summary>
        public static string AddRotation {
            get {
                return ResourceManager.GetString("AddRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alavilable abilities.
        /// </summary>
        public static string AlavilableAbilitys {
            get {
                return ResourceManager.GetString("AlavilableAbilitys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Before rotation code.
        /// </summary>
        public static string BeforeRotationCode {
            get {
                return ResourceManager.GetString("BeforeRotationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This code exequted before rotation started.
        /// </summary>
        public static string BeforeRotationCodeToolTip {
            get {
                return ResourceManager.GetString("BeforeRotationCodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drop casting.
        /// </summary>
        public static string CancelCasting {
            get {
                return ResourceManager.GetString("CancelCasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drop casting spell.
        /// </summary>
        public static string CancelCastingToolTip {
            get {
                return ResourceManager.GetString("CancelCastingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drop chanel.
        /// </summary>
        public static string CancelChanel {
            get {
                return ResourceManager.GetString("CancelChanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drop channel spell.
        /// </summary>
        public static string CancelChanelToolTip {
            get {
                return ResourceManager.GetString("CancelChanelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cencel.
        /// </summary>
        public static string Cencel {
            get {
                return ResourceManager.GetString("Cencel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close window.
        /// </summary>
        public static string CloseToolTip {
            get {
                return ResourceManager.GetString("CloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Console.
        /// </summary>
        public static string CodeConsole {
            get {
                return ResourceManager.GetString("CodeConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lua tester.
        /// </summary>
        public static string CodeExequteTitle {
            get {
                return ResourceManager.GetString("CodeExequteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run (F5).
        /// </summary>
        public static string CommandRun {
            get {
                return ResourceManager.GetString("CommandRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Constructor.
        /// </summary>
        public static string Constructor {
            get {
                return ResourceManager.GetString("Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy current ability.
        /// </summary>
        public static string CopyAbility {
            get {
                return ResourceManager.GetString("CopyAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy current profile.
        /// </summary>
        public static string CopyProfile {
            get {
                return ResourceManager.GetString("CopyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy current rotation.
        /// </summary>
        public static string CopyRotation {
            get {
                return ResourceManager.GetString("CopyRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Core.
        /// </summary>
        public static string CoreHeader {
            get {
                return ResourceManager.GetString("CoreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contains handler code abilities.
        /// </summary>
        public static string CoreHeaderToolTip {
            get {
                return ResourceManager.GetString("CoreHeaderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Curent profile: .
        /// </summary>
        public static string CurentProfile {
            get {
                return ResourceManager.GetString("CurentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current rotation.
        /// </summary>
        public static string CurrentRotation {
            get {
                return ResourceManager.GetString("CurrentRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delay.
        /// </summary>
        public static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drop current ability.
        /// </summary>
        public static string DeleteAbility {
            get {
                return ResourceManager.GetString("DeleteAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drop current profile.
        /// </summary>
        public static string DeleteProfile {
            get {
                return ResourceManager.GetString("DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drop current rotation.
        /// </summary>
        public static string DeleteRotation {
            get {
                return ResourceManager.GetString("DeleteRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile editor.
        /// </summary>
        public static string EditorTitle {
            get {
                return ResourceManager.GetString("EditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save the file in the current profile.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Common functions.
        /// </summary>
        public static string GlobalFunk {
            get {
                return ResourceManager.GetString("GlobalFunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Common functions that can be used to write the rotation..
        /// </summary>
        public static string GlobalFunkToolTip {
            get {
                return ResourceManager.GetString("GlobalFunkToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show help.
        /// </summary>
        public static string HelpToolTip {
            get {
                return ResourceManager.GetString("HelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hot key.
        /// </summary>
        public static string HotKey {
            get {
                return ResourceManager.GetString("HotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload a profile from a file.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is attacked unit.
        /// </summary>
        public static string IsAttacedTarget {
            get {
                return ResourceManager.GetString("IsAttacedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is attaced unit.
        /// </summary>
        public static string IsAttacedTargetToolTip {
            get {
                return ResourceManager.GetString("IsAttacedTargetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check in combat.
        /// </summary>
        public static string IsInCombatToolTip {
            get {
                return ResourceManager.GetString("IsInCombatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moving check.
        /// </summary>
        public static string IsMovingCheck {
            get {
                return ResourceManager.GetString("IsMovingCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If true, then there is a check if the character is moving before you cast..
        /// </summary>
        public static string IsMovingCheckToolTip {
            get {
                return ResourceManager.GetString("IsMovingCheckToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Without GCD.
        /// </summary>
        public static string IsNotHCD {
            get {
                return ResourceManager.GetString("IsNotHCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indicates that the ability has no global cooldown.
        /// </summary>
        public static string IsNotHCDToolTip {
            get {
                return ResourceManager.GetString("IsNotHCDToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Range check.
        /// </summary>
        public static string IsRangeCheck {
            get {
                return ResourceManager.GetString("IsRangeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking reach the target (does not work for some spells).
        /// </summary>
        public static string IsRangeCheckToolTip {
            get {
                return ResourceManager.GetString("IsRangeCheckToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is spell known.
        /// </summary>
        public static string IsSpellKnownCheck {
            get {
                return ResourceManager.GetString("IsSpellKnownCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check whether the player (or pet) knows a spell..
        /// </summary>
        public static string IsSpellKnownCheckToolTip {
            get {
                return ResourceManager.GetString("IsSpellKnownCheckToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use in combat.
        /// </summary>
        public static string IsUseIncombat {
            get {
                return ResourceManager.GetString("IsUseIncombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download the file from the list of abilities.
        /// </summary>
        public static string LoadAbilityList {
            get {
                return ResourceManager.GetString("LoadAbilityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimise.
        /// </summary>
        public static string Minimise {
            get {
                return ResourceManager.GetString("Minimise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moving.
        /// </summary>
        public static string MovingStates_Moving {
            get {
                return ResourceManager.GetString("MovingStates_Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string MovingStates_Moving_ToolTip {
            get {
                return ResourceManager.GetString("MovingStates_Moving_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        public static string MovingStates_None {
            get {
                return ResourceManager.GetString("MovingStates_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string MovingStates_None_ToolTip {
            get {
                return ResourceManager.GetString("MovingStates_None_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not moving.
        /// </summary>
        public static string MovingStates_NotMoving {
            get {
                return ResourceManager.GetString("MovingStates_NotMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string MovingStates_NotMoving_ToolTip {
            get {
                return ResourceManager.GetString("MovingStates_NotMoving_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ability name.
        /// </summary>
        public static string NameToolTip {
            get {
                return ResourceManager.GetString("NameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not selected prosess.
        /// </summary>
        public static string NotSelectedProcessMessage {
            get {
                return ResourceManager.GetString("NotSelectedProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process: .
        /// </summary>
        public static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use a notice of proс.
        /// </summary>
        public static string ProcNotifyerToolTip {
            get {
                return ResourceManager.GetString("ProcNotifyerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;XML files (*.xml)|*.xml|All files (*.*)|*.*&quot;.
        /// </summary>
        public static string ProfileFileMask {
            get {
                return ResourceManager.GetString("ProfileFileMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile info.
        /// </summary>
        public static string ProfileInfo {
            get {
                return ResourceManager.GetString("ProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload profiles.
        /// </summary>
        public static string ReloadToolTip {
            get {
                return ResourceManager.GetString("ReloadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rotation.
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code.
        /// </summary>
        public static string Rotation_Code {
            get {
                return ResourceManager.GetString("Rotation_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Rotation_Code_ToolTip {
            get {
                return ResourceManager.GetString("Rotation_Code_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note.
        /// </summary>
        public static string Rotation_Note {
            get {
                return ResourceManager.GetString("Rotation_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Rotation_Note_ToolTip {
            get {
                return ResourceManager.GetString("Rotation_Note_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tick delay:.
        /// </summary>
        public static string Rotation_TickDelay {
            get {
                return ResourceManager.GetString("Rotation_TickDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tick delay.
        /// </summary>
        public static string Rotation_TickDelayToolTip {
            get {
                return ResourceManager.GetString("Rotation_TickDelayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rotation count: .
        /// </summary>
        public static string RotationCount {
            get {
                return ResourceManager.GetString("RotationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rotation list.
        /// </summary>
        public static string RotationList {
            get {
                return ResourceManager.GetString("RotationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить текущий профиль.
        /// </summary>
        public static string SaveToolTip {
            get {
                return ResourceManager.GetString("SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delay on next spell.
        /// </summary>
        public static string SetRecastDelay {
            get {
                return ResourceManager.GetString("SetRecastDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The delay in the next utterance of this spell.
        /// </summary>
        public static string SetRecastDelayToolTip {
            get {
                return ResourceManager.GetString("SetRecastDelayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spell.
        /// </summary>
        public static string Spell {
            get {
                return ResourceManager.GetString("Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spell Id.
        /// </summary>
        public static string SpellIdToolTip {
            get {
                return ResourceManager.GetString("SpellIdToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Target type.
        /// </summary>
        public static string TargetToolTip {
            get {
                return ResourceManager.GetString("TargetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yanitta.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update adress.
        /// </summary>
        public static string UpdAdress {
            get {
                return ResourceManager.GetString("UpdAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check updates.
        /// </summary>
        public static string UpdateToolTip {
            get {
                return ResourceManager.GetString("UpdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Death Knight.
        /// </summary>
        public static string WowClass_DeathKnight {
            get {
                return ResourceManager.GetString("WowClass_DeathKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Druid.
        /// </summary>
        public static string WowClass_Druid {
            get {
                return ResourceManager.GetString("WowClass_Druid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hunter.
        /// </summary>
        public static string WowClass_Hunter {
            get {
                return ResourceManager.GetString("WowClass_Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mage.
        /// </summary>
        public static string WowClass_Mage {
            get {
                return ResourceManager.GetString("WowClass_Mage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monk.
        /// </summary>
        public static string WowClass_Monk {
            get {
                return ResourceManager.GetString("WowClass_Monk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paladin.
        /// </summary>
        public static string WowClass_Paladin {
            get {
                return ResourceManager.GetString("WowClass_Paladin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Priest.
        /// </summary>
        public static string WowClass_Priest {
            get {
                return ResourceManager.GetString("WowClass_Priest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rogue.
        /// </summary>
        public static string WowClass_Rogue {
            get {
                return ResourceManager.GetString("WowClass_Rogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shaman.
        /// </summary>
        public static string WowClass_Shaman {
            get {
                return ResourceManager.GetString("WowClass_Shaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warlock.
        /// </summary>
        public static string WowClass_Warlock {
            get {
                return ResourceManager.GetString("WowClass_Warlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warrior.
        /// </summary>
        public static string WowClass_Warrior {
            get {
                return ResourceManager.GetString("WowClass_Warrior", resourceCulture);
            }
        }
    }
}
